### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by maksad** [CSAILVision/unifiedparsing#12]
I'm having trouble to run `./demo_test.sh`. 
The error happens in `unifiedparsing/models/resnet.py` at line:
[`from lib.nn import SynchronizedBatchNorm2d`](https://github.com/CSAILVision/unifiedparsing/blob/master/models/resnet.py#L6). 

It complains that:
```
raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
```

Here is the full traceback:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unifiedparsing/lib/nn/__init__.py", line 2, in <module>
    from .prroi_pool import *
  File "unifiedparsing/lib/nn/prroi_pool/__init__.py", line 12, in <module>
    from .prroi_pool import *
  File "unifiedparsing/lib/nn/prroi_pool/prroi_pool.py", line 14, in <module>
    from .functional import prroi_pool2d
  File "unifiedparsing/lib/nn/prroi_pool/functional.py", line 22, in <module>
    verbose=True
  File ".../python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File ".../python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File ".../python3.6/site-packages/torch/utils/cpp_extension.py", line 837, in _write_ninja_file_and_build
    verify_ninja_availability()
  File ".../python3.6/site-packages/torch/utils/cpp_extension.py", line 875, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
```

I'm using:
```
torch==1.0.1
torch-encoding==1.0.1
torchvision==0.2.0
ninja==1.9.0
```

**Comment by zhihengli-UR** [comment]
You can install ninja-build on your system by following the instruction in this link: [https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages](url)
