### ISSUE TITLE
No such file or directory: '/afs/csail.mit.edu/u/l/liuyingcheng/code/NetDissect/dataset_toy/ade20k/ADE20K_2016_07_26/index*.mat'

### ISSUE THREAD

**Issue by happyyuwei** [CSAILVision/unifiedparsing#2]
When I run the test demo, I found a problem.
ADE20K_2016_07_26/index*.mat can not be found.
 I think I have downloaded all the datasets you provided, but I still don't know where is the file index*.mat.I 
If you can give me some advice,  I will be very apprepriate.
FileNotFoundError: [Errno 2] No such file or directory: '/afs/csail.mit.edu/u/l/liuyingcheng/code/NetDissect/dataset_toy/ade20k/ADE20K_2016_07_26/index*.mat'

**Comment by Tete-Xiao** [comment]
Sorry the repo is still under construction. We're solving some of the problems, since the original project wasn't written with PyTorch. It shouldn't take very long. Thanks for your interest!

**Comment by Tete-Xiao** [comment]
Hey,
The pre-trained model has been released!

**Comment by happyyuwei** [comment]
Thank you!

**Comment by tsingjinyun** [comment]
@Tete-Xiao ,i try hard to download dataset and config env, but 
sh demo_test.sh 
Namespace(arch_decoder='ppm_bilinear_deepsup', arch_encoder='resnet50_dilated8', batch_size=1, fc_dim=2048, gpu_id=0, imgMaxSize=1000, imgSize=[300, 400, 500, 600], model_path='baseline-resnet50_dilated8-ppm_bilinear_deepsup', num_class=150, num_val=-1, padding_constant=8, result='./', segm_downsampling_rate=8, suffix='_epoch_20.pth', test_img='ADE_val_00001519.jpg')
Traceback (most recent call last):
  File "test.py", line 214, in <module>
    main(args)
  File "test.py", line 121, in main
    weights=args.weights_encoder)
  File "/export/diskpool/unifiedparsing/models/models.py", line 180, in build_encoder
    raise Exception('Architecture undefined!')
Exception: Architecture undefined!

**Comment by qiuyinglin** [comment]
@Tete-Xiao when i tried to run demo_test.sh file, i still get error: 

FileNotFoundError: [Errno 2] No such file or directory: './broden_dataset/ade20k/ADE20K_2016_07_26/index*.mat'

i see previous above thread, can't find the answer. can you please help me?

**Comment by happyyuwei** [comment]
You have to download the dataset before running the demo_test. If you have done, index*.mat would be found under the dictionary: ./broden_dataset/ade20k/ADE20K_2016_07_26

**Comment by qiuyinglin** [comment]
@happyyuwei1994 
thank you! i finally run ./download_Broden+.sh to download all necessary data, and the error is gone.

**Comment by happyyuwei** [comment]
@qiuyinglin 
you are welcome.

**Comment by poweryin** [comment]
@tsingjinyun  hi,I also have same problems,can you tell me how to deal with the problem? thank you
