### ISSUE TITLE
TypeError while running Step 2 of Training on Broden+ 

### ISSUE THREAD

**Issue by richylyq** [CSAILVision/unifiedparsing#20]
encountered the TypeError while running the training of the default network, i was just following the commands stated on the README
```
Traceback (most recent call last):
  File "train.py", line 339, in <module>
    main(args)
  File "train.py", line 232, in main
    train(segmentation_module, iterator_train, optimizers, history, epoch, args)
  File "train.py", line 45, in train
    ret = segmentation_module(batch_data)
  File "/home/rohit/miniconda2/envs/unifiedparsing/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rohit/Desktop/projects/unifiedparsing/models/models.py", line 66, in forward
    if feed_dict['source_idx'] == 0:
TypeError: list indices must be integers or slices, not str
```

**Comment by richylyq** [comment]
So when i print the feed_dict to see what is the source_idx and i gotten this
```
[{'img': tensor([[[[ -18.9801,  -19.9801,  -19.9801,  ...,    0.0000,    0.0000,
             ...
         [0, 0, 0,  ..., 0, 0, 0]]]), 'valid_material': tensor([1, 1]), 'source_idx': tensor(1)}]
```
